name: pina
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+22

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  in_app_purchase: ^3.1.13
  excel: ^4.0.2
  flutter_dotenv: ^5.1.0
  firebase_core: ^2.30.0
  firebase_messaging: ^14.7.10
  supabase_flutter: ^2.0.0
  flutter_facebook_auth: ^6.0.0 
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  http: ^1.6.0
  font_awesome_flutter: ^10.12.0
  image_picker: ^1.2.1
  google_sign_in: ^6.2.1
  visibility_detector: ^0.4.0+2
  file_picker: ^10.3.7
  langchain: ^0.8.0+1
  langchain_openai: ^0.8.0+1
  share_plus: ^12.0.1
  read_pdf_text: ^0.3.1
  docx_to_text: ^1.0.1
  path_provider: ^2.1.5
  video_player: ^2.8.1
  
  record: ^5.1.2
  permission_handler: ^12.0.1
  pdf: ^3.11.3
  image_gallery_saver_plus: ^4.0.1
  gal: ^2.3.2
  hive_flutter: ^1.1.0
  duckduckgo_search: ^0.2.0
  google_generative_ai: ^0.4.7
  audioplayers: ^6.5.1
  url_launcher: ^6.2.6
  printing: ^5.14.2
  open_file: ^3.3.3
  speech_to_text: ^7.0.1
  google_fonts: ^6.2.1
  rive: ^0.13.20
  flutter_svg: ^2.2.0
  flutter_local_notifications: ^17.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  record_linux: ^1.0.0
  record_platform_interface: ^1.0.9

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/study_abroad/
    - assets/template/
    - assets/template/RiveAssets/
    - assets/template/icons/
    - assets/template/Backgrounds/
    - assets/icons/facebook.png
    - assets/icons/google.png
    - assets/icons/instagram.png
    - assets/study_abroad/germany1.jpg
    - assets/study_abroad/germany2.png
    - assets/study_abroad/visa.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/template/Fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/template/Fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/template/Fonts/Inter-SemiBold.ttf
          weight: 600
